version: '2'
services:
    jhipsterheroku-app:
        image: jhipsterheroku
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterheroku-postgresql:5432/jhipsterheroku
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterheroku-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterheroku-postgresql
